#!/bin/bash
REPO_GROUPS="default,-darwin,-_devices"
REPO_GROUPS+=",_devices_google_gs2"
# REPO_GROUPS+=",_devices_oneplus_sdm845"
REPO_GROUPS+=",_devices_oneplus_sm8150"
REPO_GROUPS+=",_devices_oneplus_sm8250"
REPO_GROUPS+=",_devices_oneplus_sm8350"
REPO_GROUPS+=",_devices_oneplus_sm8750"
# REPO_GROUPS+=",_devices_samsung_gts4lv"
REPO_GROUPS+=",_devices_sony_nile"
REPO_GROUPS+=",_devices_sony_sm6375"
# REPO_GROUPS+=",_devices_xiaomi_msm8996"

repo init --git-lfs --no-clone-bundle -u ssh://git@github.com/LineageOS/android.git -b refs/changes/31/460731/6 -g $REPO_GROUPS
mkdir -p vendor/extra && cp ~/.android/adbkey.pub vendor/extra/adbkey.pub
