#!/bin/bash
repo init --git-lfs --no-clone-bundle -u ssh://git@github.com/LineageOS/android.git -b lineage-22.0 -g default,-darwin
mkdir -p vendor/extra && cp ~/.android/adbkey.pub vendor/extra/adbkey.pub
