#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        #${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py $@
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# build/make
repopick -f 332045 # Don't enforce vintf kernel requirements when building without LTO

# frameworks/base
repopick -f 357988 # Set DEFAULT_ADB_ALLOWED_CONNECTION_TIME to 0

# vendor/lineage
repopick 381293 # config: Build Glimpse

wait
