#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"
GERRIT_USERNAME="$(git config review.review.lineageos.org.username)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "${@: -1} - " ; ssh lineage-gerrit gerrit query ${@: -1} --format=JSON | jq --slurp -r '.[0].status'
    else
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py \
            -g "ssh://$GERRIT_USERNAME@review.lineageos.org:29418" $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# build/make
# repopick -f 332045 # Don't enforce vintf kernel requirements when building without LTO

# android
repopickchain 436442 # lineage: Temporarily track lineage-22.2 for certain repos

# device/generic/goldfish
repopickchain 435541 # goldfish: Remove NavigationBarMode2ButtonOverlay

# device/google/contexthub
repopick 433315 # contexthub: sensorhal: allow building it again with Android.bp

# device/qcom/sepolicy_vndr/sm8750
repopickchain 437756 # sepolicy: Remove sysfs_udc label

# external/e2fsprogs
repopickchain 433337 # e2fsck: Loosen fscrypt_policy struct size check

# frameworks/base
repopickchain 434605 # fixup! Firewall: Transport-based toggle support (1/3)

# frameworks/native
repopickchain 433378 # InputDispatcher: On keypress, deliver keycode to pokeUserActivity

# frameworks/opt/telephony
repopickchain 433395 # telephony: Make "Do not ask again" functional

# hardware/libhardware
repopickchain 433441 # libhardware: Add new display types.

# hardware/qcom-caf/sm8650/display
repopickchain 437787 # gralloc: avoid calling property_get() on every buffer allocation

# hardware/qcom-caf/sm8650/audio/agm
repopickchain 437334 # agm: disable mem logger support

# hardware/qcom-caf/sm8750/audio/pal
repopickchain 437868 # vui_interface: Address more compilation errors

# hardware/qcom-caf/sm8750/audio/primary-hal
repopickchain 437495 # libbaterylistener: Remove unused HIDL health dependencies

# hardware/qcom-caf/sm8750/dataipa
repopickchain 437553 # dataipa: Disable all the debugging

# hardware/qcom-caf/sm8750/display/hal
repopickchain 437788 # gralloc: avoid calling property_get() on every buffer allocation

# kernel/configs
repopickchain 433459 # p/android-4.4: Bump min LTS version

# kernek/oneplus/sm8150
repopick -p 439270 # Merge commit 'refs/changes/46/437246/6' of https://github.com/LineageOS/android_kernel_qcom_sm8150 into HEAD

# packages/apps/Car/Settings
repopickchain 433464 # VolumeSettingsPreferenceController: Fix NPE when changing volumes

# packages/apps/Car/SystemUI
repopick 433465 # CarSystemUI: Fixes after QPR2

# packages/apps/Settings
repopickchain 437655 # fixup! Fix background data clobbering other policies

# packages/apps/SettingsIntelligence
repopickchain 433482 # Style search bar to match new Settings UI

# packages/apps/TvSettings
repopickchain 433752 # TvSettings: Fix energy optimization setting

# packages/modules/Bluetooth
repopickchain 433508 # BondStateMachine: Check name for validity before access

# packages/modules/Connectivity
repopickchain 433518 # netd: Remove <5.4 kernel restrictions

# system/bpf
repopickchain 433560 # bpfloader: prog names are only valid on 4.15+

# system/core
repopickchain 437212 # init: add a hook before parsing system properties

# system/libhidl
repopick 433596 # libhidlmemory: mark as recovery_available

# system/logging
repopickchain 433600 # liblog: Always report as debuggable when building userdebug/eng

# vendor/qcom/opensource/audio-hal/st-hal-ar
repopickchain 437007 # st-hal-ar: Add dependency on libarpal_headers

wait
