#!/bin/bash
PATCHSETS=$(ssh lineage-gerrit gerrit query $1 --current-patch-set --format=JSON | jq 'select(.number != null) | [.number,.currentPatchSet.number] | join(",")' | xargs echo)
REVIEW=""

case "$2" in
    *-2*)
        REVIEW+=" --code-review -2"
        ;;
    *-1*)
        REVIEW+=" --code-review -1"
        ;;
    *+1*)
        REVIEW+=" --code-review +1"
        ;;
    *+2*)
        REVIEW+=" --code-review +2"
        ;;
esac

case "$2" in
    *-v*|*-V*)
        REVIEW+=" --verified -1"
        ;;
    *+v*|*+V*)
        REVIEW+=" --verified +1"
        ;;
esac

if [[ -z "$REVIEW" ]]; then
    echo $PATCHSETS | xargs ssh lineage-gerrit gerrit review ${@:2}
else
    echo $PATCHSETS | xargs ssh lineage-gerrit gerrit review $REVIEW
fi
